


export const strings = {
  fa: {
    // General
    appName: 'رویای شیرین من',
    save: 'ذخیره',
    saveChanges: 'ذخیره تغییرات',
    cancel: 'لغو',
    edit: 'ویرایش',
    delete: 'حذف',
    confirm: 'بله',
    deny: 'خیر',
    loading: 'در حال بارگذاری...',
    preparing: 'در حال آماده‌سازی...',
    submit: 'ثبت',
    done: 'انجام شد',
    optional: 'اختیاری',
    requiredFields: 'لطفا تمامی فیلدهای الزامی را پر کنید.',
    date: 'تاریخ',
    time: 'ساعت',
    description: 'توضیحات',
    success: 'موفقیت',
    error: 'خطا',
    example: 'مثال',
    user: 'کاربر',
    photo: 'عکس',
    addPhoto: 'افزودن عکس',
    changePhoto: 'تغییر عکس',

    // Views & Titles
    dashboardTitle: 'داشبورد',
    profileTitle: 'حساب کاربری',
    settingsTitle: 'تنظیمات',
    logHistoryTitle: 'تاریخچه ثبت‌ها',
    toolsTitle: 'ابزارها',
    graphTitle: 'نمودار و گزارش',
    aiAnalysisTitle: 'تحلیل هوشمند',
    carbTableTitle: 'جدول کربوهیدرات',
    doseCalculatorTitle: 'حسابگر هوشمند',
    logBloodSugarTitle: 'ثبت قند خون',
    editBloodSugarTitle: 'ویرایش قند خون',
    logMealTitle: 'ثبت وعده غذایی',
    editMealTitle: 'ویرایش وعده غذایی',
    logActivityTitle: 'ثبت فعالیت',
    editActivityTitle: 'ویرایش فعالیت',
    logSleepTitle: 'ثبت خواب و بیداری',
    editSleepTitle: 'ویرایش خواب',
    logInsulinTitle: 'ثبت انسولین',
    editInsulinTitle: 'ویرایش انسولین',
    logMoodTitle: 'ثبت حال روزانه',
    editMoodTitle: 'ویرایش حال روزانه',
    logMedicationTitle: 'ثبت دارو',
    editMedicationTitle: 'ویرایش دارو',
    logPhysicalConditionTitle: 'ثبت وضعیت جسمانی',
    editPhysicalConditionTitle: 'ویرایش وضعیت جسمانی',
    diabetesIdCardTitle: 'کارت شناسایی دیابت',
    diabetesEncyclopedia: 'دانشنامه دیابت',


    // Bottom Nav
    navDashboard: 'داشبورد',
    navHistory: 'تاریخچه',
    navTools: 'ابزارها',
    navProfile: 'حساب',
    newLog: 'ثبت گزارش جدید',

    // Log Menu
    logMenuTitle: 'چه چیزی را می‌خواهید ثبت کنید؟',
    logMenuBloodSugar: 'قند خون',
    logMenuMeal: 'وعده غذایی',
    logMenuInsulin: 'انسولین',
    logMenuActivity: 'فعالیت',
    logMenuSleep: 'خواب',
    logMenuMood: 'حال روزانه',
    logMenuMedication: 'دارو',
    logMenuPhysicalCondition: 'وضعیت جسمانی',

    // Dashboard
    specialConditionActive: 'شرایط ویژه فعال است (بلوغ/قاعدگی)',
    summaryToday: 'خلاصه امروز',
    summaryWeek: 'خلاصه هفته',
    summaryMonth: 'خلاصه ماه',
    summaryQuarter: 'خلاصه ۳ ماه اخیر',
    avgGlucose: 'میانگین قند',
    totalInsulin: 'انسولین کل',
    totalCarbs: 'کربوهیدرات کل',
    totalActivity: 'فعالیت کل',
    estimatedBasal: 'پایه تخمینی',
    estimatedBolus: 'غذایی تخمینی',
    unit: 'واحد',
    gram: 'گرم',
    minute: 'دقیقه',
    insulinOnBoard: 'انسولین فعال (IOB)',


    // Glucose Prediction Card
    whatsYourBS: 'قند خونت الان چنده؟',
    estimateWithAI: 'تخمین هوشمند قند خون',
    estimateForMe: 'برایم تخمین بزن',
    logBSToEstimate: 'برای تخمین، ابتدا قند خون ثبت کنید',
    estimating: 'در حال تخمین...',
    estimateAt: 'تخمین در',
    compareWithReal: 'مقایسه با قند واقعی',
    lastComparison: 'آخرین مقایسه:',
    estimate: 'تخمین',
    real: 'واقعی',
    difference: 'اختلاف',
    learningMessage: 'عالیه! دارم یاد می‌گیرم.',
    whatIsThis: 'این چیه؟',
    whatIsSmartEstimation: 'تخمین هوشمند چیست؟',
    smartEstimationExplanation: 'این قابلیت با استفاده از هوش مصنوعی و بر اساس آخرین داده‌های ثبت‌شده شما (قند خون، وعده‌های غذایی، انسولین و فعالیت)، قند خون لحظه‌ای شما را تخمین می‌زند. این یک ابزار کمکی است و جایگزین تست قند خون با گلوکومتر نمی‌شود.',
    
    // Profile Screen
    userList: 'لیست کاربران',
    editUserTitle: 'ویرایش حساب کاربری',
    name: 'نام',
    birthDate: 'تاریخ تولد',
    gender: 'جنسیت',
    select: 'انتخاب کنید',
    male: 'مرد',
    female: 'زن',
    height: 'قد (سانتیمتر)',
    weight: 'وزن (کیلوگرم)',
    diabetesType: 'نوع دیابت',
    type1: 'نوع ۱',
    type2: 'نوع ۲',
    gestational: 'بارداری',
    other: 'سایر',
    basalInsulin: 'انسولین پایه',
    bolusInsulin: 'انسولین غذایی',
    injectionSitePriority: 'اولویت‌بندی محل تزریق',
    injectionSitePriorityDesc: 'محل‌هایی که انسولین در آن‌ها سریع‌تر جذب می‌شود را بالاتر قرار دهید.',
    menstrualInfo: 'اطلاعات عادت ماهیانه (اختیاری)',
    lastPeriodDate: 'تاریخ شروع آخرین دوره',
    cycleLength: 'طول دوره (روز)',
    addUser: 'افزودن کاربر جدید',
    deleteUserConfirm: 'آیا از حذف این کاربر و تمام اطلاعات ثبت شده برای او اطمینان دارید؟ این عمل غیرقابل بازگشت است.',
    emergencyContacts: 'مخاطبین اضطراری',
    addEmergencyContact: 'افزودن مخاطب اضطراری',
    phone: 'شماره تلفن',

    // Settings Screen
    quickSettings: 'تنظیمات سریع',
    displaySettings: 'تنظیمات نمایش',
    lightMode: 'روشن',
    darkMode: 'تاریک',
    autoMode: 'خودکار',
    changeTheme: 'تغییر تم رنگی',
    notifications: 'اعلان‌ها',
    notificationsDesc: 'برای یادآوری‌ها و هشدارها، اعلان‌ها را فعال کنید.',
    enableNotifications: 'فعال‌سازی اعلان‌ها',
    notificationsNotSupported: 'مرورگر شما از اعلان‌ها پشتیبانی نمی‌کند.',
    notificationsEnabled: 'اعلان‌ها با موفقیت فعال شدند!',
    notificationsBlocked: 'شما اعلان‌ها را مسدود کرده‌اید. لطفاً از تنظیمات مرورگر آن‌ها را فعال کنید.',
    summaryTimeframe: 'بازه زمانی خلاصه',
    daily: 'روزانه',
    weekly: 'هفتگی',
    monthly: 'ماهانه',
    quarterly: 'سه ماهه',
    timeFrame_daily: 'روز',
    timeFrame_weekly: 'هفته',
    timeFrame_monthly: 'ماه',
    timeFrame_quarterly: '۳ ماه',
    aiAssistant: 'دستیار هوشمند',
    aiAssistantDesc: 'فعال‌سازی تحلیل و تخمین هوشمند',
    backupRestore: 'پشتیبان‌گیری و بازیابی',
    backupRestoreDesc: 'از اطلاعات خود یک فایل پشتیبان تهیه کنید یا اطلاعات خود را از یک فایل بازیابی نمایید. این عملیات به صورت محلی در دستگاه شما انجام می‌شود.',
    backup: 'تهیه نسخه پشتیبان',
    restore: 'بازیابی از فایل',
    restoreConfirm: 'آیا از بازیابی اطلاعات از فایل پشتیبان اطمینان دارید؟ تمام اطلاعات فعلی شما پاک خواهد شد.',
    backupSuccess: 'فایل پشتیبان با موفقیت دانلود شد.',
    backupError: 'خطایی در هنگام تهیه پشتیبان رخ داد.',
    restoreSuccess: 'اطلاعات با موفقیت بازیابی شد.',
    restoreError: 'فایل پشتیبان معتبر نیست یا در خواندن آن مشکلی پیش آمده است.',
    contactUs: 'ارتباط با ما',
    contactUsDesc: 'با استفاده از لینک‌های زیر می‌توانید با ما در ارتباط باشید:',
    eitaaGroup: 'گروه ایتا',
    eitaaChannel: 'کانال آموزه‌های دیابت رویای شیرین',
    version: 'نسخه',
    language: 'زبان',
    noInternetConnection: 'اتصال اینترنت برقرار نیست.',
    aboutAppTitle: 'درباره رویای شیرین',
    aboutAppMessage: `
**رویای شیرین، دستیار شما برای مدیریت دیابت.**
هدف ما توانمندسازی شما برای زندگی سالم‌تر و شادتر با دیابت است.

**امکانات کلیدی:**

* **ثبت جامع و آسان:**
  - ثبت قند خون، وعده‌های غذایی، انسولین (پایه و غذایی)، فعالیت ورزشی، حالات روحی و شرایط جسمانی (بیماری، استرس و...).

* **ابزارهای محاسباتی دقیق:**
  - محاسبه خودکار فاکتورهای مهم دیابت (ICR, ISF, TDD) بر اساس سوابق شما.
  - محاسبه‌گر دوز اصلاحی و انسولین فعال در بدن (IOB).
  - جدول کامل کربوهیدرات مواد غذایی ایرانی و خارجی.

* **دستیار هوشمند (به زودی فعال می‌شود):**
  - **تحلیل هوشمند:** دریافت تحلیل جامع از الگوهای قند خون.
  - **تخمین قند لحظه‌ای:** پیش‌بینی هوشمند قند خون فعلی شما.
  - **پیشنهاد دوز هوشمند:** دریافت پیشنهاد دوز انسولین برای وعده‌ها.
  - **چت‌بات سلامتی:** پاسخ به سوالات دیابتی شما.

* **گزارش‌های حرفه‌ای برای پزشک:**
  - خروجی PDF و CSV (اکسل) از نمودارها و سوابق کامل جهت ارائه به پزشک.
  - گزارش جامع یک صفحه‌ای با تمام اطلاعات کلیدی.

* **شخصی‌سازی و ویژگی‌های کاربردی:**
  - **دانشنامه دیابت:** دسترسی به اطلاعات معتبر و کاربردی در مورد مدیریت دیابت.
  - تم‌های رنگی متنوع و حالت تاریک/روشن.
  - کارت شناسایی دیابت و حالت اضطراری برای مواقع ضروری.
  - قابلیت تعیین اهداف و پیگیری پیشرفت.
`,

    // Log Screens
    bloodSugarLevel: 'میزان قند خون (mg/dL)',
    estimatedValue: 'مقدار تخمین زده شده',
    enterRealValue: 'حالا لطفاً مقدار واقعی را برای مقایسه وارد کنید.',
    mealType: 'نوع وعده',
    totalCarbsGrams: 'کربوهیدرات کل (گرم)',
    injectedInsulin: 'انسولین تزریقی',
    injectionSite: 'محل تزریق انسولین',
    postMealActivity: 'فعالیت بعد از غذا',
    fattyMeal: 'وعده غذایی چرب با تاثیر تاخیری',
    activityType: 'نوع فعالیت',
    durationMinutes: 'مدت زمان (دقیقه)',
    wakeUpDate: 'تاریخ بیدار شدن',
    sleepTime: 'ساعت خواب',
    wakeTime: 'ساعت بیداری',
    insulinType: 'نوع انسولین',
    insulinDoseUnits: 'میزان انسولین (واحد)',
    howAreYouFeeling: 'حال روحی شما چطور است؟',
    howIsYourBodyFeeling: 'وضعیت جسمانی شما چطور است؟',
    medicationName: 'نام دارو',
    medicationDose: 'دوز مصرفی',
    medicationUnit: 'واحد (مثل میلی‌گرم، قرص)',
    physicalCondition: 'وضعیت جسمانی',

    // History Screen
    noDataYet: 'هنوز هیچ داده‌ای ثبت نشده است.',

    // Mood & Condition options
    moodHappy: 'خوشحالی',
    moodCalm: 'آرامش',
    moodSad: 'ناراحتی',
    moodStressed: 'استرس',
    moodAnxious: 'اضطراب',
    moodScared: 'ترس',
    moodAngry: 'خشم',
    moodCrying: 'گریه',
    moodHeadache: 'سردرد',
    moodStomachache: 'دل درد',
    moodFeverChills: 'تب و لرز',
    moodNosebleed: 'خون دماغ',
    moodColdFlu: 'سرماخوردگی',

    // Graph Screen
    timeInRange: 'زمان در محدوده (TIR)',
    low: 'پایین',
    normal: 'نرمال',
    high: 'بالا',
    noTIRData: 'برای نمایش TIR، حداقل ۲ مقدار قند خون ثبت کنید.',
    glucoseChart: 'نمودار قند خون',
    noChartData: 'برای نمایش نمودار، حداقل ۲ مقدار قند خون ثبت کنید.',
    loadingChart: 'در حال بارگذاری نمودار...',
    exports: 'دریافت خروجی',
    chartPDF: 'نمودار (PDF)',
    chartJPG: 'نمودار (JPG)',
    comprehensiveReportPDF: 'دانلود گزارش PDF',
    excelFileCSV: 'فایل اکسل (CSV)',
    preparingReport: 'در حال آماده‌سازی گزارش...',
    comprehensiveDiabetesReport: 'گزارش جامع دیابت',
    reportDate: 'تاریخ گزارش',
    userInfo: 'اطلاعات کاربر',
    
    // Tools Screen
    aiToolsDesc: 'تحلیل هوشمند، چت‌بات، پیش‌بینی و...',
    goalsAndAchievements: 'اهداف و دستاوردها',
    goalsAndAchievementsDesc: 'برای خود هدف تعیین کنید و پیشرفتتان را دنبال کنید',
    emergencyMode: 'حالت اضطراری',
    emergencyModeDesc: 'ارسال پیام اضطراری به مخاطبین با موقعیت مکانی',
    dailyTipAndChallenge: 'نکته و چالش روزانه',
    dailyTipAndChallengeDesc: 'دریافت نکته هوشمند برای افزایش انگیزه',
    carbCountWithCamera: 'شمارش کربوهیدرات با دوربین',
    carbCountWithCameraDesc: 'از غذای خود عکس بگیرید تا کربوهیدرات آن تخمین زده شود',
    doseCalculator: 'حسابگر دوز',
    doseCalculatorDesc: 'محاسبه دوز اصلاحی و کربوهیدرات',
    smartAnalysis: 'تحلیل هوشمند',
    smartAnalysisDesc: 'دریافت تحلیل و توصیه‌های هوشمند',
    chartsAndReports: 'نمودارها و خروجی‌ها',
    chartsAndReportsDesc: 'مشاهده نمودار TIR و سایر خروجی‌ها',
    comprehensiveReportForDoctor: 'گزارش جامع جهت ارائه به پزشک',
    comprehensiveReportForDoctorDesc: 'دانلود گزارش کامل و رسمی برای پزشک',
    carbTable: 'جدول کربوهیدرات مواد غذایی',
    carbTableDesc: 'مشاهده کربوهیدرات مواد غذایی مختلف',
    healthChatbot: 'چت‌بات سلامتی',
    healthChatbotDesc: 'سوالات خود را از دستیار هوشمند بپرسید',
    futurePrediction: 'پیش‌بینی روند قند',
    futurePredictionDesc: 'روند قند خون خود را در ساعات آینده ببینید',
    comingSoon: 'به زودی...',
    smartDoseDescShort: 'دریافت دوز پیشنهادی هوشمند برای وعده غذایی',
    diabetesIdCardTool: 'کارت شناسایی دیابت',
    diabetesIdCardToolDesc: 'ایجاد و دانلود کارت شناسایی دیابت برای مواقع ضروری',
    downloadAsImage: 'دانلود به صورت عکس',
    inCaseOfEmergency: 'در مواقع اضطراری',
    inCaseOfEmergencyDesc: 'اگر قادر به پاسخگویی نبودم، لطفاً قند خون من را چک کنید. در صورت افت قند، به من مواد شیرین بدهید و با اورژانس تماس بگیرید.',
    diabetesEncyclopediaDesc: 'اطلاعات معتبر و کاربردی در مورد دیابت',
    
    // Chatbot
    askMeAnything: 'از من بپرسید...',

    // Dose Calculator
    correctionDose: 'دوز اصلاحی',
    carbAndCalories: 'کربوهیدرات و کالری',
    smartMealDose: 'دوز هوشمند غذا',
    currentGlucose: 'قند فعلی',
    targetGlucose: 'قند هدف',
    calculate: 'محاسبه کن',
    calculatorDisclaimer: 'این فرمول فقط یک ابزار کمکی است و جایگزین توصیه‌های پزشکی نیست.',
    smartCarbSearch: 'جستجوی هوشمند کربوهیدرات',
    search: 'جستجو',
    byCarb: 'بر اساس کربوهیدرات',
    byEnergy: 'بر اساس انرژی و چربی',
    totalEnergy: 'انرژی کل (کالری)',
    fatGrams: 'چربی (گرم)',
    carbUnit: 'واحد کربوهیدرات',
    requiredInsulin: 'انسولین مورد نیاز',
    smartDoseDesc: 'با توجه به سابقه تزریق، ورزش و شرایط شما، یک دوز هوشمند برای وعده غذایی خود دریافت کنید.',
    getSmartDose: 'دریافت دوز هوشمند',
    analyzing: 'در حال تحلیل...',
    suggestedSmartDose: 'دوز پیشنهادی هوشمند',
    iobWarning: 'توجه: {iobValue} واحد انسولین فعال در بدن شما وجود دارد. دوز اصلاحی پیشنهادی با در نظر گرفتن این مقدار کاهش یافته است.',
    iobInfo: 'توجه: شما حدود {iobValue} واحد انسولین فعال در بدن دارید.',

    // Camera Modal
    cameraErrorTitle: 'خطا در دسترسی به دوربین',
    cameraUnsupported: 'دوربین در این مرورگر پشتیبانی نمی‌شود.',
    permissionDenied: 'دسترسی به دوربین رد شد. لطفاً از تنظیمات مرورگر، دسترسی به دوربین را برای این سایت فعال کنید.',
    cameraNotFound: 'هیچ دوربینی یافت نشد. لطفاً مطمئن شوید دوربین دستگاه شما فعال است.',
    cameraGenericError: 'خطایی در دسترسی به دوربین رخ داد. لطفاً صفحه را رفرش کرده و دوباره تلاش کنید.',
    gotIt: 'متوجه شدم',

    // AI
    aiError: 'متاسفانه در ارتباط با سرویس هوش مصنوعی خطایی رخ داد. لطفا بعدا دوباره تلاش کنید.',
    aiAnalysisWelcome: 'تحلیل هوشمند داده‌ها',
    aiAnalysisDesc: 'با استفاده از هوش مصنوعی، الگوهای قند خون خود را شناسایی کنید و توصیه‌های شخصی‌سازی شده برای مدیریت بهتر دیابت دریافت نمایید.',
    startAnalysis: 'شروع تحلیل',
    
    // Emergency
    addEmergencyContactFirst: 'ابتدا از بخش حساب کاربری، یک مخاطب اضطراری اضافه کنید.',
    geolocationNotSupported: 'موقعیت‌یابی توسط مرورگر شما پشتیبانی نمی‌شود.',
    geolocationPermissionDenied: 'دسترسی به موقعیت مکانی رد شد. لطفاً از تنظیمات مرورگر دسترسی را فعال کنید.',
    geolocationPositionUnavailable: 'اطلاعات موقعیت مکانی در دسترس نیست.',
    geolocationTimeout: 'دریافت موقعیت مکانی با وقفه زمانی مواجه شد.',
    geolocationUnknownError: 'یک خطای ناشناخته در دریافت موقعیت مکانی رخ داد.',
    emergencyAlert: 'هشدار اضطراری',
    sendAlert: 'ارسال هشدار',
    holdToActivate: '(ارسال پیامک)',
    noneDefined: 'تعریف نشده',

    // Goals
    activeGoals: 'اهداف فعال',
    noActiveGoals: 'هیچ هدف فعالی وجود ندارد.',
    completedGoals: 'اهداف تکمیل شده',
    noCompletedGoals: 'هنوز هیچ هدفی را تکمیل نکرده‌اید.',
    goalType_avg_glucose: 'میانگین قند خون',
    goalType_daily_activity: 'فعالیت روزانه',
    target: 'هدف',
    current: 'وضعیت فعلی',
    abandonGoal: 'لغو هدف',
    goalUnit_avg_glucose: 'mg/dL',
    goalUnit_daily_activity: 'دقیقه/روز',
    addNewGoal: 'افزودن هدف جدید',
    invalidTarget: 'لطفاً یک مقدار هدف معتبر وارد کنید.',
    goalType: 'نوع هدف',
    targetValue: 'مقدار هدف',
    timeFrame: 'بازه زمانی',
    addGoal: 'افزودن هدف',

    // Encyclopedia
    encyclopediaDisclaimer: 'اطلاعات این بخش صرفاً جهت آگاهی‌رسانی است و نباید جایگزین مشاوره با پزشک یا تیم درمانی شما شود. همیشه برای تصمیمات پزشکی با متخصص خود مشورت کنید.',
    encyclopedia_what_is_diabetes_title: 'دیابت چیست؟',
    encyclopedia_what_is_diabetes_content: `**نوع ۱:** در دیابت نوع ۱، بدن انسولین تولید نمی‌کند. سیستم ایمنی به سلول‌های تولیدکننده انسولین در پانکراس حمله می‌کند. این نوع دیابت معمولاً در کودکان و جوانان تشخیص داده می‌شود و نیاز به تزریق روزانه انسولین دارد.
**نوع ۲:** در دیابت نوع ۲، بدن به درستی از انسولین استفاده نمی‌کند (مقاومت به انسولین) یا به اندازه کافی انسولین تولید نمی‌کند. این نوع شایع‌تر است و معمولاً با رژیم غذایی، ورزش و داروها کنترل می‌شود، هرچند گاهی نیاز به انسولین نیز پیدا می‌کند.`,
    encyclopedia_bg_management_title: 'مدیریت قند خون',
    encyclopedia_bg_management_content: `**محدوده هدف:** محدوده قند خون هدف برای اکثر افراد بین ۸۰ تا ۱۸۰ mg/dL است. قند ناشتا معمولاً باید زیر ۱۳۰ و قند بعد از غذا زیر ۱۸۰ باشد. این محدوده‌ها ممکن است برای هر فرد متفاوت باشد؛ با پزشک خود مشورت کنید.
**افت قند (هیپوگلیسمی):** قند خون زیر ۷۰. علائم: لرزش، تعریق، سرگیجه، گرسنگی شدید. درمان: قانون ۱۵-۱۵. ۱۵ گرم کربوهیدرات ساده (مثل آبمیوه) مصرف کنید، ۱۵ دقیقه صبر کنید و دوباره قند را چک کنید.
**قند بالا (هیپرگلیسمی):** قند خون بالای ۱۸۰. علائم: تشنگی زیاد، تکرر ادرار، خستگی. درمان: نوشیدن آب، فعالیت سبک (اگر قند زیر ۲۵۰ است) و تزریق دوز اصلاحی طبق دستور پزشک.`,
    encyclopedia_carb_counting_title: 'شمارش کربوهیدرات',
    encyclopedia_carb_counting_content: 'کربوهیدرات‌ها بیشترین تأثیر را بر قند خون دارند. یادگیری شمارش کربوهیدرات به شما کمک می‌کند تا دوز انسولین غذایی (بولوس) را دقیق‌تر محاسبه کنید. از جدول کربوهیدرات برنامه برای کمک استفاده کنید. هر «واحد کربوهیدرات» معادل ۱۵ گرم کربوهیدرات است.',
    encyclopedia_insulin_sites_title: 'انسولین و محل‌های تزریق',
    encyclopedia_insulin_sites_content: 'انسولین برای کنترل قند خون حیاتی است. سرعت جذب آن به محل تزریق بستگی دارد. ترتیب سرعت جذب: شکم (سریع‌ترین) > بازو > ران > باسن (کندترین). چرخش منظم محل تزریق برای جلوگیری از تجمع چربی (لیپوهیپرتروفی) ضروری است.',
    encyclopedia_exercise_role_title: 'نقش ورزش',
    encyclopedia_exercise_role_content: 'فعالیت بدنی منظم به بهبود حساسیت به انسولین و کنترل قند خون کمک می‌کند. حداقل ۱۵۰ دقیقه ورزش هوازی متوسط در هفته توصیه می‌شود. همیشه قبل از ورزش قند خون خود را چک کنید و در صورت نیاز، یک میان‌وعده کربوهیدراتی مصرف نمایید.',
    encyclopedia_general_care_title: 'مراقبت‌های عمومی',
    encyclopedia_general_care_content: `**مراقبت از پا:** هر روز پاهای خود را برای هرگونه زخم، تاول یا قرمزی بررسی کنید. پاها را خشک و تمیز نگه دارید و از کفش راحت استفاده کنید.
**نوشیدن آب:** هیدراته ماندن به کلیه‌ها برای دفع قند اضافی از طریق ادرار کمک می‌کند و از غلیظ شدن خون جلوگیری می‌نماید.`,

    // Dashboard Modal Content
    modal_noDataSourceMessage: 'برای محاسبه، لطفا تزریق‌های انسولین خود را ثبت کنید یا وزن خود را در حساب کاربری وارد نمایید.',
    modal_isfTitle: 'ISF (فاکتور حساسیت به انسولین)',
    modal_isfMessage_logs: 'بر اساس میانگین ۱۴ روز گذشته و با در نظر گرفتن سن شما، تزریق هر یک واحد انسولین قند خونتان را حدود {isfString} واحد کاهش می‌دهد.',
    modal_isfMessage_weight: 'این مقدار به صورت تخمینی (بر اساس وزن و سن) محاسبه شده است. بر این اساس، هر یک واحد انسولین قند خون شما را حدود {isfString} واحد کاهش می‌دهد. برای محاسبه دقیق‌تر، لطفا تزریق‌های انسولین خود را ثبت کنید.',
    modal_icrTitle: 'ICR (نسبت انسولین به کربوهیدرات)',
    modal_icrMessage_logs: 'بر اساس میانگین ۱۴ روز گذشته و با در نظر گرفتن سن شما، تزریق هر یک واحد انسولین حدود {icrString} گرم کربوهیدرات را پوشش می‌دهد.',
    modal_icrMessage_weight: 'این مقدار به صورت تخمینی (بر اساس وزن و سن) محاسبه شده است. بر این اساس، هر یک واحد انسولین حدود {icrString} گرم کربوهیدرات را پوشش می‌دهد. برای محاسبه دقیق‌تر، لطفا تزریق‌های انسولین خود را ثبت کنید.',
    modal_bmiTitle: 'BMI (شاخص توده بدنی)',
    modal_bmiRangeUnderweight: 'کمبود وزن',
    modal_bmiRangeNormal: 'وزن نرمال',
    modal_bmiRangeOverweight: 'اضافه وزن',
    modal_bmiRangeObese: 'چاقی',
    modal_bmiDescWithValue: 'شاخص توده بدنی شما {bmi} است که در محدوده **{range}** قرار می‌گیرد.',
    modal_bmiDescNoValue: 'لطفاً قد و وزن خود را در حساب کاربری وارد کنید.',
    modal_ffTitle: 'FF (فاکتور غذایی)',
    modal_ffMessage: 'این فاکتور نشان می‌دهد که به ازای هر ۱۵ گرم کربوهیدرات، تقریباً به {ff} واحد انسولین نیاز دارید. این محاسبه بر اساس ICR شما (که با توجه به سن و سوابق تنظیم شده) انجام شده است.',
    modal_a1cTitle: 'A1C تخمینی',
    modal_a1cDescWithValue: 'این مقدار بر اساس میانگین قند خون شما در ۹۰ روز گذشته ({avgBloodSugar} mg/dL) تخمین زده شده است. \n\n**توجه:** این عدد یک تخمین است و جایگزین آزمایش خون A1C در آزمایشگاه نمی‌شود.',
    modal_a1cDescNoValue: 'برای تخمین A1C، حداقل یک مورد قند خون در ۹۰ روز گذشته باید ثبت شده باشد.',
    modal_tddTitle: 'TDD (کل انسولین روزانه)',
    modal_tddMessage_logs: 'میانگین کل انسولین روزانه شما (TDD) بر اساس تزریق‌های ۱۴ روز گذشته، حدود **{tdd} واحد** است.',
    modal_tddMessage_weight: 'کل انسولین روزانه شما (TDD) به صورت تخمینی و بر اساس نصف وزن شما حدود **{tdd} واحد** محاسبه شده است. برای محاسبه دقیق‌تر، لطفا تزریق‌های انسولین خود را ثبت کنید.',
    modal_basalTitle: 'انسولین پایه (Basal)',
    modal_bolusTitle: 'انسولین غذایی (Bolus)',
    modal_noDataSourceInsulinMessage: 'برای محاسبه دقیق‌تر، لطفا تزریق‌های انسولین خود را به طور منظم ثبت کنید.',
    modal_tddSourceFromWeight: 'بر اساس نصف وزن شما',
    modal_tddSourceFromLogs: 'بر اساس کل انسولین روزانه شما',
    modal_basalMessage_logs: 'میانگین انسولین پایه تزریقی شما در ۱۴ روز گذشته حدود **{value} واحد** بوده است. این مقدار برای کنترل قند خون در حالت ناشتا و بین وعده‌های غذایی استفاده می‌شود.',
    modal_basalMessage_tdd: 'این مقدار به صورت تخمینی (۵۰٪ از کل انسولین روزانه تخمینی شما که {tddSourceText} محاسبه شده) حدود **{value} واحد** می‌باشد. {noDataSourceMessage}',
    modal_basalDescNoValue: 'اطلاعات کافی برای تخمین انسولین پایه وجود ندارد. لطفا تزریق‌های انسولین پایه خود را ثبت کنید.',
    modal_bolusMessage_logs: 'میانگین انسولین غذایی تزریقی شما در ۱۴ روز گذشته حدود **{value} واحد** بوده است. این مقدار برای پوشش کربوهیدرات وعده‌های غذایی و اصلاح قند خون بالا استفاده می‌شود.',
    modal_bolusMessage_tdd: 'این مقدار به صورت تخمینی (۵۰٪ از کل انسولین روزانه تخمینی شما که {tddSourceText} محاسبه شده) حدود **{value} واحد** می‌باشد. {noDataSourceMessage}',
    modal_bolusDescNoValue: 'اطلاعات کافی برای تخمین انسولین غذایی وجود ندارد. لطفا تزریق‌های انسولین برای وعده‌های غذایی را ثبت کنید.',
    modal_iobTitle: 'انسولین فعال در بدن (IOB) چیست؟',
    modal_iobMessage: 'IOB مقدار انسولین بولوس (غذایی) است که از تزریق‌های قبلی هنوز در بدن شما فعال است و قند خون را پایین می‌آورد. این برنامه، انسولین فعال را تا ۴ ساعت پس از تزریق در نظر می‌گیرد. دانستن مقدار IOB به جلوگیری از «تجمع انسولین» و افت قند خون شدید کمک می‌کند.',
  },
  en: {
    // General
    appName: 'My Sweet Dream',
    save: 'Save',
    saveChanges: 'Save Changes',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Yes',
    deny: 'No',
    loading: 'Loading...',
    preparing: 'Preparing...',
    submit: 'Submit',
    done: 'Done',
    optional: 'Optional',
    requiredFields: 'Please fill in all required fields.',
    date: 'Date',
    time: 'Time',
    description: 'Description',
    success: 'Success',
    error: 'Error',
    example: 'Example',
    user: 'User',
    photo: 'Photo',
    addPhoto: 'Add Photo',
    changePhoto: 'Change Photo',

    // Views & Titles
    dashboardTitle: 'Dashboard',
    profileTitle: 'Profile',
    settingsTitle: 'Settings',
    logHistoryTitle: 'Log History',
    toolsTitle: 'Tools',
    graphTitle: 'Charts & Reports',
    aiAnalysisTitle: 'AI Analysis',
    carbTableTitle: 'Carb Table',
    doseCalculatorTitle: 'Smart Calculator',
    logBloodSugarTitle: 'Log Blood Sugar',
    editBloodSugarTitle: 'Edit Blood Sugar',
    logMealTitle: 'Log Meal',
    editMealTitle: 'Edit Meal',
    logActivityTitle: 'Log Activity',
    editActivityTitle: 'Edit Activity',
    logSleepTitle: 'Log Sleep',
    editSleepTitle: 'Edit Sleep',
    logInsulinTitle: 'Log Insulin',
    editInsulinTitle: 'Edit Insulin',
    logMoodTitle: 'Log Mood',
    editMoodTitle: 'Edit Mood',
    logMedicationTitle: 'Log Medication',
    editMedicationTitle: 'Edit Medication',
    logPhysicalConditionTitle: 'Log Physical Condition',
    editPhysicalConditionTitle: 'Edit Physical Condition',
    diabetesIdCardTitle: 'Diabetes ID Card',
    diabetesEncyclopedia: 'Diabetes Encyclopedia',

    // Bottom Nav
    navDashboard: 'Dashboard',
    navHistory: 'History',
    navTools: 'Tools',
    navProfile: 'Profile',
    newLog: 'Add New Log',

    // Log Menu
    logMenuTitle: 'What do you want to log?',
    logMenuBloodSugar: 'Blood Sugar',
    logMenuMeal: 'Meal',
    logMenuInsulin: 'Insulin',
    logMenuActivity: 'Activity',
    logMenuSleep: 'Sleep',
    logMenuMood: 'Mood',
    logMenuMedication: 'Medication',
    logMenuPhysicalCondition: 'Physical Condition',

    // Dashboard
    specialConditionActive: 'Special condition is active (Puberty/Menstruation)',
    summaryToday: "Today's Summary",
    summaryWeek: "This Week's Summary",
    summaryMonth: "This Month's Summary",
    summaryQuarter: "Last 3 Months' Summary",
    avgGlucose: 'Avg. Glucose',
    totalInsulin: 'Total Insulin',
    totalCarbs: 'Total Carbs',
    totalActivity: 'Total Activity',
    estimatedBasal: 'Est. Basal',
    estimatedBolus: 'Est. Bolus',
    unit: 'unit',
    gram: 'g',
    minute: 'min',
    insulinOnBoard: 'Insulin on Board (IOB)',

    // Glucose Prediction Card
    whatsYourBS: 'What is your BG now?',
    estimateWithAI: 'Smart Glucose Estimation',
    estimateForMe: 'Estimate for me',
    logBSToEstimate: 'Log BG to enable estimation',
    estimating: 'Estimating...',
    estimateAt: 'Estimated at',
    compareWithReal: 'Compare with Real BG',
    lastComparison: 'Last Comparison:',
    estimate: 'Estimate',
    real: 'Real',
    difference: 'Difference',
    learningMessage: "Great! I'm learning.",
    whatIsThis: "What's this?",
    whatIsSmartEstimation: 'What is Smart Estimation?',
    smartEstimationExplanation: 'This feature uses AI based on your latest logged data (blood sugar, meals, insulin, and activity) to estimate your current blood glucose. This is an assistive tool and does not replace testing with a glucometer.',

    // Profile Screen
    userList: 'User List',
    editUserTitle: 'Edit User Profile',
    name: 'Name',
    birthDate: 'Birth Date',
    gender: 'Gender',
    select: 'Select',
    male: 'Male',
    female: 'Female',
    height: 'Height (cm)',
    weight: 'Weight (kg)',
    diabetesType: 'Diabetes Type',
    type1: 'Type 1',
    type2: 'Type 2',
    gestational: 'Gestational',
    other: 'Other',
    basalInsulin: 'Basal Insulin',
    bolusInsulin: 'Bolus Insulin',
    injectionSitePriority: 'Injection Site Priority',
    injectionSitePriorityDesc: 'Order sites from fastest to slowest insulin absorption.',
    menstrualInfo: 'Menstrual Cycle Info (Optional)',
    lastPeriodDate: 'Last Period Start Date',
    cycleLength: 'Cycle Length (days)',
    addUser: 'Add New User',
    deleteUserConfirm: 'Are you sure you want to delete this user and all their data? This action cannot be undone.',
    emergencyContacts: 'Emergency Contacts',
    addEmergencyContact: 'Add Emergency Contact',
    phone: 'Phone Number',

    // Settings Screen
    quickSettings: 'Quick Settings',
    displaySettings: 'Display Settings',
    lightMode: 'Light',
    darkMode: 'Dark',
    autoMode: 'Auto',
    changeTheme: 'Change Color Theme',
    notifications: 'Notifications',
    notificationsDesc: 'Enable notifications for reminders and alerts.',
    enableNotifications: 'Enable Notifications',
    notificationsNotSupported: 'Your browser does not support notifications.',
    notificationsEnabled: 'Notifications enabled successfully!',
    notificationsBlocked: 'You have blocked notifications. Please enable them in your browser settings.',
    summaryTimeframe: 'Summary Timeframe',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    timeFrame_daily: 'Day',
    timeFrame_weekly: 'Week',
    timeFrame_monthly: 'Month',
    timeFrame_quarterly: '3 Mos',
    aiAssistant: 'AI Assistant',
    aiAssistantDesc: 'Enable AI analysis and estimations',
    backupRestore: 'Backup & Restore',
    backupRestoreDesc: 'Backup your data to a file or restore from a backup. This operation is performed locally on your device.',
    backup: 'Backup Data',
    restore: 'Restore from File',
    restoreConfirm: 'Are you sure you want to restore from this backup file? All your current data will be overwritten.',
    backupSuccess: 'Backup file downloaded successfully.',
    backupError: 'An error occurred during backup.',
    restoreSuccess: 'Data restored successfully.',
    restoreError: 'Invalid backup file or an error occurred while reading it.',
    contactUs: 'Contact Us',
    contactUsDesc: 'You can reach out to us via the following links:',
    eitaaGroup: 'Eitaa Group',
    eitaaChannel: 'Sweet Dream Diabetes Channel',
    version: 'Version',
    language: 'Language',
    noInternetConnection: 'No Internet Connection.',
    aboutAppTitle: 'About Sweet Dream',
    aboutAppMessage: `
**Sweet Dream, your assistant for diabetes management.**
Our goal is to empower you to live a healthier and happier life with diabetes.

**Key Features:**
* **Comprehensive & Easy Logging:**
  - Log blood sugar, meals, insulin (basal and bolus), exercise, moods, and physical conditions (illness, stress, etc.).

* **Accurate Calculation Tools:**
  - Automatic calculation of important diabetes factors (ICR, ISF, TDD) based on your history.
  - Correction dose calculator and Insulin on Board (IOB) tracking.
  - Extensive carb table for various food items.
  
* **AI Assistant (Coming Soon):**
  - **Smart Analysis:** Get comprehensive analysis of your blood sugar patterns.
  - **Real-time Glucose Estimation:** Intelligently predict your current blood sugar.
  - **Smart Dose Suggestion:** Receive insulin dose suggestions for meals.
  - **Health Chatbot:** Get answers to your diabetes-related questions.

* **Professional Doctor Reports:**
  - PDF and CSV (Excel) exports of charts and complete logs to share with your doctor.
  - A comprehensive one-page report with all key information.

* **Personalization & Practical Features:**
  - **Diabetes Encyclopedia:** Access reliable and practical information about diabetes management.
  - Multiple color themes and light/dark mode.
  - Diabetes ID card and Emergency Mode for critical situations.
  - Ability to set goals and track your progress.
`,

    // Log Screens
    bloodSugarLevel: 'Blood Sugar Level (mg/dL)',
    estimatedValue: 'Estimated value',
    enterRealValue: 'Now, please enter the actual value for comparison.',
    mealType: 'Meal Type',
    totalCarbsGrams: 'Total Carbs (grams)',
    injectedInsulin: 'Injected Insulin',
    injectionSite: 'Injection Site',
    postMealActivity: 'Post-Meal Activity',
    fattyMeal: 'Fatty meal with delayed effect',
    activityType: 'Activity Type',
    durationMinutes: 'Duration (minutes)',
    wakeUpDate: 'Wake-up Date',
    sleepTime: 'Sleep Time',
    wakeTime: 'Wake-up Time',
    insulinType: 'Insulin Type',
    insulinDoseUnits: 'Insulin Dose (units)',
    howAreYouFeeling: 'How are you feeling mentally?',
    howIsYourBodyFeeling: 'How are you feeling physically?',
    medicationName: 'Medication Name',
    medicationDose: 'Dose',
    medicationUnit: 'Unit (e.g. mg, tablet)',
    physicalCondition: 'Physical Condition',

    // History Screen
    noDataYet: 'No data has been logged yet.',

    // Mood & Condition options
    moodHappy: 'Happy',
    moodCalm: 'Calm',
    moodSad: 'Sad',
    moodStressed: 'Stressed',
    moodAnxious: 'Anxious',
    moodScared: 'Scared',
    moodAngry: 'Angry',
    moodCrying: 'Crying',
    moodHeadache: 'Headache',
    moodStomachache: 'Stomachache',
    moodFeverChills: 'Fever & Chills',
    moodNosebleed: 'Nosebleed',
    moodColdFlu: 'Cold / Flu',

    // Graph Screen
    timeInRange: 'Time in Range (TIR)',
    low: 'Low',
    normal: 'Normal',
    high: 'High',
    noTIRData: 'Log at least 2 blood sugar values to see TIR.',
    glucoseChart: 'Blood Glucose Chart',
    noChartData: 'Log at least 2 blood sugar values to see the chart.',
    loadingChart: 'Loading chart...',
    exports: 'Exports',
    chartPDF: 'Chart (PDF)',
    chartJPG: 'Chart (JPG)',
    comprehensiveReportPDF: 'Download PDF Report',
    excelFileCSV: 'Excel File (CSV)',
    preparingReport: 'Preparing report...',
    comprehensiveDiabetesReport: 'Comprehensive Diabetes Report',
    reportDate: 'Report Date',
    userInfo: 'User Information',

    // Tools Screen
    aiToolsDesc: 'AI analysis, chatbot, predictions...',
    goalsAndAchievements: 'Goals & Achievements',
    goalsAndAchievementsDesc: 'Set goals for yourself and track your progress',
    emergencyMode: 'Emergency Mode',
    emergencyModeDesc: 'Send an emergency message with your location',
    dailyTipAndChallenge: 'Daily Tip & Challenge',
    dailyTipAndChallengeDesc: 'Get smart tips for motivation',
    carbCountWithCamera: 'Carb Count with Camera',
    carbCountWithCameraDesc: 'Take a photo of your food to estimate carbs',
    doseCalculator: 'Dose Calculator',
    doseCalculatorDesc: 'Calculate correction and carb doses',
    smartAnalysis: 'Smart Analysis',
    smartAnalysisDesc: 'Get AI-powered analysis and recommendations',
    chartsAndReports: 'Charts and Exports',
    chartsAndReportsDesc: 'View TIR chart and other exports',
    comprehensiveReportForDoctor: 'Comprehensive Report for Doctor',
    comprehensiveReportForDoctorDesc: 'Download a complete and official report for your doctor',
    carbTable: 'Food Carb Table',
    carbTableDesc: 'Look up carbohydrate content of foods',
    healthChatbot: 'Health Chatbot',
    healthChatbotDesc: 'Ask your questions to the AI assistant',
    futurePrediction: 'Glucose Trend Prediction',
    futurePredictionDesc: 'See your blood sugar trend in the coming hours',
    comingSoon: 'Coming soon...',
    smartDoseDescShort: 'Get a smart dose suggestion for your meal',
    diabetesIdCardTool: 'Diabetes ID Card',
    diabetesIdCardToolDesc: 'Create and download a diabetes ID card for emergencies',
    downloadAsImage: 'Download as Image',
    inCaseOfEmergency: 'In Case of Emergency',
    inCaseOfEmergencyDesc: 'If I am unresponsive, please check my blood sugar. If low, give me sugar. Please call emergency services.',
    diabetesEncyclopediaDesc: 'Reliable and practical information about diabetes',

    
    // Chatbot
    askMeAnything: 'Ask me anything...',

    // Dose Calculator
    correctionDose: 'Correction Dose',
    carbAndCalories: 'Carbs & Calories',
    smartMealDose: 'Smart Meal Dose',
    currentGlucose: 'Current BG',
    targetGlucose: 'Target BG',
    calculate: 'Calculate',
    calculatorDisclaimer: '⚠️ This calculator is an aid and does not replace medical advice.',
    smartCarbSearch: 'Smart Carb Search',
    search: 'Search',
    byCarb: 'By Carbohydrate',
    byEnergy: 'By Energy & Fat',
    totalEnergy: 'Total Energy (kcal)',
    fatGrams: 'Fat (g)',
    carbUnit: 'Carb Units',
    requiredInsulin: 'Required Insulin',
    smartDoseDesc: 'Get a smart bolus suggestion for your meal based on your history, exercise, and personal conditions.',
    getSmartDose: 'Get Smart Dose',
    analyzing: 'Analyzing...',
    suggestedSmartDose: 'Suggested Smart Dose',
    iobWarning: 'Note: You have {iobValue} units of active insulin. The suggested correction dose has been reduced accordingly.',
    iobInfo: 'Note: You have about {iobValue} units of active insulin.',

    // Camera Modal
    cameraErrorTitle: 'Camera Access Error',
    cameraUnsupported: 'Camera is not supported in this browser.',
    permissionDenied: 'Camera permission was denied. Please enable camera access for this site in your browser settings.',
    cameraNotFound: 'No camera was found. Please ensure your device camera is enabled.',
    cameraGenericError: 'An error occurred while accessing the camera. Please refresh the page and try again.',
    gotIt: 'Got it',

    // AI
    aiError: 'Sorry, an error occurred while communicating with the AI service. Please try again later.',
    aiAnalysisWelcome: 'Smart Data Analysis',
    aiAnalysisDesc: 'Utilize AI to identify patterns in your blood glucose and receive personalized recommendations for better diabetes management.',
    startAnalysis: 'Start Analysis',

    // Emergency
    addEmergencyContactFirst: 'Please add an emergency contact in your profile first.',
    geolocationNotSupported: 'Geolocation is not supported by your browser.',
    geolocationPermissionDenied: 'Geolocation permission was denied. Please enable it in browser settings.',
    geolocationPositionUnavailable: 'Location information is unavailable.',
    geolocationTimeout: 'The request to get user location timed out.',
    geolocationUnknownError: 'An unknown error occurred while getting location.',
    emergencyAlert: 'Emergency Alert',
    sendAlert: 'Send Alert',
    holdToActivate: '(Sends SMS)',
    noneDefined: 'None defined',

    // Goals
    activeGoals: 'Active Goals',
    noActiveGoals: 'You have no active goals.',
    completedGoals: 'Completed Goals',
    noCompletedGoals: "You haven't completed any goals yet.",
    goalType_avg_glucose: 'Average Blood Glucose',
    goalType_daily_activity: 'Daily Activity',
    target: 'Target',
    current: 'Current',
    abandonGoal: 'Abandon Goal',
    goalUnit_avg_glucose: 'mg/dL',
    goalUnit_daily_activity: 'min/day',
    addNewGoal: 'Add New Goal',
    invalidTarget: 'Please enter a valid target value.',
    goalType: 'Goal Type',
    targetValue: 'Target Value',
    timeFrame: 'Time Frame',
    addGoal: 'Add Goal',

     // Encyclopedia
    encyclopediaDisclaimer: 'The information in this section is for educational purposes only and should not replace advice from your doctor or healthcare team. Always consult your specialist for medical decisions.',
    encyclopedia_what_is_diabetes_title: 'What is Diabetes?',
    encyclopedia_what_is_diabetes_content: `**Type 1:** In type 1 diabetes, the body does not produce insulin. The immune system attacks the insulin-producing cells in the pancreas. This type is usually diagnosed in children and young adults and requires daily insulin injections.
**Type 2:** In type 2 diabetes, the body does not use insulin properly (insulin resistance) or does not produce enough insulin. This type is more common and is usually managed with diet, exercise, and medications, although sometimes insulin is also needed.`,
    encyclopedia_bg_management_title: 'Blood Sugar Management',
    encyclopedia_bg_management_content: `**Target Range:** The target blood sugar range for most people is between 80 to 180 mg/dL. Fasting glucose should typically be below 130 and post-meal glucose below 180. These ranges may vary for each individual; consult your doctor.
**Hypoglycemia (Low BG):** Blood sugar below 70. Symptoms: shaking, sweating, dizziness, extreme hunger. Treatment: The 15-15 rule. Consume 15 grams of simple carbs (like juice), wait 15 minutes, and check your blood sugar again.
**Hyperglycemia (High BG):** Blood sugar above 180. Symptoms: excessive thirst, frequent urination, fatigue. Treatment: Drink water, light activity (if BG is below 250), and take a correction dose as prescribed by your doctor.`,
    encyclopedia_carb_counting_title: 'Carbohydrate Counting',
    encyclopedia_carb_counting_content: 'Carbohydrates have the most significant impact on blood sugar. Learning to count carbs helps you calculate your mealtime (bolus) insulin dose more accurately. Use the app\'s carb table for assistance. One "carb unit" is equivalent to 15 grams of carbohydrates.',
    encyclopedia_insulin_sites_title: 'Insulin & Injection Sites',
    encyclopedia_insulin_sites_content: 'Insulin is vital for controlling blood sugar. Its absorption speed depends on the injection site. The order of absorption speed is: Abdomen (fastest) > Arm > Thigh > Buttocks (slowest). Regular rotation of injection sites is essential to prevent fatty lumps (lipohypertrophy).',
    encyclopedia_exercise_role_title: 'Role of Exercise',
    encyclopedia_exercise_role_content: 'Regular physical activity helps improve insulin sensitivity and blood sugar control. At least 150 minutes of moderate aerobic exercise per week is recommended. Always check your blood sugar before exercising and have a carbohydrate snack if needed.',
    encyclopedia_general_care_title: 'General Care',
    encyclopedia_general_care_content: `**Foot Care:** Check your feet daily for any sores, blisters, or redness. Keep your feet clean and dry, and wear comfortable shoes.
**Hydration:** Staying hydrated helps the kidneys flush out excess sugar through urine and prevents blood from becoming too concentrated.`,

    // Dashboard Modal Content
    modal_noDataSourceMessage: 'To calculate, please log your insulin injections or enter your weight in your profile.',
    modal_isfTitle: 'ISF (Insulin Sensitivity Factor)',
    modal_isfMessage_logs: 'Based on the average of the last 14 days and considering your age, one unit of insulin lowers your blood sugar by about {isfString} units.',
    modal_isfMessage_weight: 'This value is estimated (based on weight and age). Accordingly, one unit of insulin lowers your blood sugar by about {isfString} units. For a more accurate calculation, please log your insulin injections.',
    modal_icrTitle: 'ICR (Insulin-to-Carb Ratio)',
    modal_icrMessage_logs: 'Based on the average of the last 14 days and considering your age, one unit of insulin covers about {icrString} grams of carbohydrates.',
    modal_icrMessage_weight: 'This value is estimated (based on weight and age). Accordingly, one unit of insulin covers about {icrString} grams of carbohydrates. For a more accurate calculation, please log your insulin injections.',
    modal_bmiTitle: 'BMI (Body Mass Index)',
    modal_bmiRangeUnderweight: 'Underweight',
    modal_bmiRangeNormal: 'Normal weight',
    modal_bmiRangeOverweight: 'Overweight',
    modal_bmiRangeObese: 'Obesity',
    modal_bmiDescWithValue: 'Your Body Mass Index (BMI) is {bmi}, which falls within the **{range}** range.',
    modal_bmiDescNoValue: 'Please enter your height and weight in your profile.',
    modal_ffTitle: 'FF (Food Factor)',
    modal_ffMessage: 'This factor indicates that for every 15 grams of carbohydrates, you need approximately {ff} units of insulin. This is calculated based on your ICR (adjusted for age and history).',
    modal_a1cTitle: 'Estimated A1C',
    modal_a1cDescWithValue: 'This value is estimated based on your average blood glucose over the last 90 days ({avgBloodSugar} mg/dL).\n\n**Note:** This is an estimate and does not replace a laboratory A1C test.',
    modal_a1cDescNoValue: 'To estimate A1C, at least one blood glucose reading must be logged in the last 90 days.',
    modal_tddTitle: 'TDD (Total Daily Dose)',
    modal_tddMessage_logs: 'Your average Total Daily Dose (TDD) based on the last 14 days of injections is about **{tdd} units**.',
    modal_tddMessage_weight: 'Your Total Daily Dose (TDD) is estimated to be about **{tdd} units** based on half your body weight. For a more accurate calculation, please log your insulin injections.',
    modal_basalTitle: 'Basal Insulin',
    modal_bolusTitle: 'Bolus Insulin',
    modal_noDataSourceInsulinMessage: 'For a more accurate calculation, please log your insulin injections regularly.',
    modal_tddSourceFromWeight: 'based on half your body weight',
    modal_tddSourceFromLogs: 'based on your total daily insulin',
    modal_basalMessage_logs: 'Your average basal insulin dose over the last 14 days is about **{value} units**. This is used to control blood sugar levels while fasting and between meals.',
    modal_basalMessage_tdd: 'This value is estimated (50% of your estimated TDD, which is calculated {tddSourceText}) to be about **{value} units**. {noDataSourceMessage}',
    modal_basalDescNoValue: 'Not enough data to estimate basal insulin. Please log your basal insulin injections.',
    modal_bolusMessage_logs: 'Your average bolus insulin dose over the last 14 days is about **{value} units**. This is used to cover carbohydrates from meals and correct high blood sugar.',
    modal_bolusMessage_tdd: 'This value is estimated (50% of your estimated TDD, which is calculated {tddSourceText}) to be about **{value} units**. {noDataSourceMessage}',
    modal_bolusDescNoValue: 'Not enough data to estimate bolus insulin. Please log your mealtime insulin injections.',
    modal_iobTitle: 'What is Insulin on Board (IOB)?',
    modal_iobMessage: 'IOB is the amount of bolus (meal) insulin still active in your body from previous injections, which continues to lower your blood glucose. This app considers insulin to be active for up to 4 hours after injection. Knowing your IOB helps prevent "insulin stacking" and severe hypoglycemia.',
  }
};